### ISSUE TITLE
Adding metadata to Charge request

### ISSUE THREAD

**Issue by riaz-bordie-cko** [CKOTech/checkout-magento2-plugin#1]
Hi Dmitry,
As agreed, I'm creating an Issue instead of using GMAIL for this request.

Can we please add metadata when creating a charge following the below structure?

server: Server and Client information (browser)
quote_id: Magento quote ID (if still applicable on Magento V2)
magento_version: Magento version
plugin_version: The version of the your Magento/Checkout plugin the merchant is using
lib_version: the version of our PHP core library (if you are using the our PHP core library)
integration_type: JS/API/Kit
time: Merchant's server time

Thanks

**Comment by mage2pro** [comment]
I have implemented it in the [1.0.6](https://github.com/CKOTech/checkout-magento2-plugin/releases/tag/1.0.6) version.  
Unfortunately, Checkout.com does not show the metadata in the merchant's interface ([unlike Stripe](https://mage2.pro/t/topic/932)), so I have checked the correctness of the metadata with a debugger:
![04](https://cloud.githubusercontent.com/assets/83204/16361676/ae75e7c6-3ba0-11e6-954c-49468cfaaf49.png)

**Comment by nicolas-maalouf-cko** [comment]
Tested successfully.

@riaz-bordie-cko you can close the issue
