### ISSUE TITLE
Unable to place order when not signed in

### ISSUE THREAD

**Issue by nicolas-maalouf-cko** [CKOTech/checkout-magento2-plugin#10]
@mage2pro when trying to place an order without being signed in I get the below error:

main.CRITICAL: exception 'Zend_Filter_Exception' with message 'Report ID: webapi-578e4be72f255; Message: Система не смогла распознать значение «889a7d5ec0a9f7d07ad6d5bb8d4c1a64» типа «string» как целое число.' in /var/www/html/magento2/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:194

This didn't use to happen before the latest commits you pushed.

**Comment by mage2pro** [comment]
I have fixed it in the [1.4.26](https://github.com/mage2pro/core/releases/tag/1.4.26) core version.
