### ISSUE TITLE
Module stopped to work

### ISSUE THREAD

**Issue by afred79** [CKOTech/checkout-magento2-plugin#11]
Hello.

We installed your extension for payment Checkout.com a some time ago and it worked it sandbox mode.
The module versions were:
mage2pro/checkout.com - 1.0.37
mage2pro/core - 1.5.17

A few days ago it stopped to work. We've updated. New versions are:
mage2pro/checkout.com - 1.0.47
mage2pro/core - 1.6.16

But there are another errors. It generate exceptions in logs.
We decreased mage2pro/core version to 1.6.10 manually as it require in composer.lock for module mage2pro/checkout.com. But we still have the same error.

The log file "mage2pro.exception-2016-08-17--13-55.log.zip" with exception is attached.

Please add some advice how to install correct version of checkout.com module.

Thank you.

[mage2pro.exception-2016-08-17--13-55.zip](https://github.com/CKOTech/checkout-magento2-plugin/files/422611/mage2pro.exception-2016-08-17--13-55.zip)

**Comment by mage2pro** [comment]
Fixed in the 1.0.48 version.

**Comment by afred79** [comment]
Thank you for quick response.
New version had updated, but there is another error.

There are attached screenshot with message on checkout page and exception log file. Credentials were updated and saved in configuration. Please check it out.

![checkout com error message](https://cloud.githubusercontent.com/assets/2360929/17773194/d311461e-6555-11e6-8c55-8a76bcbb404f.png)

[exception-2016-08-18--15-06.zip](https://github.com/CKOTech/checkout-magento2-plugin/files/424822/exception-2016-08-18--15-06.zip)

**Comment by mage2pro** [comment]
Use separate topics for separate issues.
