### ISSUE TITLE
The error after updating to version 1.0.48. 

### ISSUE THREAD

**Issue by afred79** [CKOTech/checkout-magento2-plugin#12]
The module was updated to version 1.0.48. 
Please look on the error: attached screenshot with message on checkout page and exception log file.
Thank you

[exception-2016-08-18--15-06.zip](https://github.com/CKOTech/checkout-magento2-plugin/files/425054/exception-2016-08-18--15-06.zip)
![checkout com error message](https://cloud.githubusercontent.com/assets/2360929/17776005/801b5658-6563-11e6-8089-93dac9191c71.png)

**Comment by mage2pro** [comment]
Fixed in 1.0.49.
