### ISSUE TITLE
Remove references to Stripe

### ISSUE THREAD

**Issue by nicolas-maalouf-cko** [CKOTech/checkout-magento2-plugin#2]
Concerned files are Method.php and config.xml.

Inside workspace.xml there's referencing to "show_stripe_button". Is this Checkout.com's button?

**Comment by mage2pro** [comment]
Reference an exact GitHub project's code line in an exact version.

**Comment by nicolas-maalouf-cko** [comment]
Latest version.

Do you want me to send you the lines where Stripe is mentioned?

**Comment by mage2pro** [comment]
https://www.google.com/search?q=github+reference+a+code+line
An example:
https://github.com/CKOTech/checkout-magento2-plugin/blob/1.0.6/composer.json#L8-L13

**Comment by nicolas-maalouf-cko** [comment]
### Method.php

https://github.com/CKOTech/checkout-magento2-plugin/blob/1.0.6/Method.php#L118
https://github.com/CKOTech/checkout-magento2-plugin/blob/1.0.6/Method.php#L127
https://github.com/CKOTech/checkout-magento2-plugin/blob/1.0.6/Method.php#L482
https://github.com/CKOTech/checkout-magento2-plugin/blob/1.0.6/Method.php#L714

### config.xml

https://github.com/CKOTech/checkout-magento2-plugin/blob/1.0.6/etc/config.xml#L18-L25

**Comment by mage2pro** [comment]
I made it in the [1.0.7](https://github.com/CKOTech/checkout-magento2-plugin/releases/tag/1.0.7) version.
