### ISSUE TITLE
Put back mage2pro/checkout.com package in packagist

### ISSUE THREAD

**Issue by nicolas-maalouf-cko** [CKOTech/checkout-magento2-plugin#4]
composer require --prefer-source mage2pro/checkout.com:* function now breaks as the mage2pro/checkout.com seems to be missing.

**Comment by mage2pro** [comment]
It is because the Git repositiry has been moved.
You should declare the new repository location in https://packagist.org

**Comment by mage2pro** [comment]
And you should setup GitHub and Packagist integration in GitHub too, so Packagist will be notified about new module's releases:
![02](https://cloud.githubusercontent.com/assets/83204/16414941/5caea3fc-3d43-11e6-89a2-d1d695ec9c14.png)
