### ISSUE TITLE
Uncaught error on orders with 3D-Secure

### ISSUE THREAD

**Issue by nicolas-maalouf-cko** [CKOTech/checkout-magento2-plugin#5]
With 3D-Secure enabled before being redirected to the 3D page the console logs [this error](https://snag.gy/f9YU3r.jpg)

It doesn't seem to affect the flow as the redirection back to magento is successful and the orders goes through.

**Comment by mage2pro** [comment]
If *it do not affect the flow as the redirection back to magento is successful and the orders goes through* then it is not an issue.
