### ISSUE TITLE
[URGENT] Merchant issue: "Maximum function nesting level of '256' reached, aborting"

### ISSUE THREAD

**Issue by riaz-bordie-cko** [CKOTech/checkout-magento2-plugin#7]
@mage2pro @ravish-ramrakha-cko @nicolas-maalouf-cko 

Hi Dmitry,
We have an urgent issue with the plugin.

Merchant said:
Mage2Pro Core Module, Df\Framework\Plugin\View\Layout > aroundRenderNonCachedElement()

Apparently, as it's used everywhere, it is causing **Fatal error: Maximum function nesting level of '256' reached, aborting!**

They tried to increase the nesting level but the page still does not load.

Please let us know what can be done here. Thanks

**Comment by mage2pro** [comment]
I need SSH access to the problem server.
