### ISSUE TITLE
Checkout flow broken on Place Order (internal server error)

### ISSUE THREAD

**Issue by nicolas-maalouf-cko** [CKOTech/checkout-magento2-plugin#9]
Checkout flow seems broken since [this commit](https://github.com/CKOTech/checkout-magento2-plugin/commit/550f1d4c834f232a478417bdb124c261b1ba0fd2).

I now get the below error when clicking on "Place Order":

jquery.js:9666 POST [MY_MAGENTO_INSTANCE_URL]/magento2/rest/default/V1/dfe-checkout-com/75781a5fb308b971180a6e2e4bb23cf3/place-order 500 (Internal Server Error)

[This commit](https://github.com/CKOTech/checkout-magento2-plugin/commit/6ebe06fe9b0b065a4036010de0182c7f103eed8c) didn't fix the issue

**Comment by mage2pro** [comment]
[How to diagnose «500 Internal Server Error»?](https://mage2.pro/t/topic/854)

**Comment by nicolas-maalouf-cko** [comment]
@mage2pro 

Here is the error:

PHP Fatal error:  Undefined class constant 'RESPONSE' in /var/www/html/magento2/vendor/mage2pro/checkout.com/Method.php on line 654, referer: http://[MYWEBSITEURL].com/magento2/checkout/

Tested on 1.0.21

**Comment by mage2pro** [comment]
I have fixed it in the [1.0.22](https://github.com/CKOTech/checkout-magento2-plugin/releases/tag/1.0.22) version.
